# dbt_transform/ecommerce/models/schema.yml
version: 2

models:
  - name: dim_customers
    description: "Dimension table for customers with their metrics"
    columns:
      - name: customer_id
        description: "Primary key for customers"
        tests:
          - unique
          - not_null
      - name: customer_city
        tests:
          - not_null
      - name: total_orders
        description: "Total number of orders for this customer"
        tests:
          - not_null

  - name: dim_products
    description: "Dimension table for products"
    columns:
      - name: product_id
        description: "Primary key for products"
        tests:
          - unique
          - not_null
      - name: product_category_name
        tests:
          - not_null
      - name: price_range
        tests:
          - accepted_values:
              values:
                - 'Low'
                - 'Medium'
                - 'High'

  - name: fact_orders
    description: "Fact table for orders"
    columns:
      - name: order_id
        description: "The unique identifier for each order"
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - relationships:
              to: ref('dim_customers')
              field: customer_id
      - name: product_id
        tests:
          - relationships:
              to: ref('dim_products')
              field: product_id
      - name: total_order_value
        tests:
          - not_null