# dbt_transform/ecommerce/models/schema.yml
version: 2

models:
  - name: fact_orders
    description: "Table de faits des commandes"
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: total_order_value
        tests:
          - not_null

  - name: dim_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: customer_city
        tests:
          - not_null

  - name: dim_products
    columns:
      - name: product_id
        tests:
          - unique
          - not_null
      - name: product_category_name
        tests:
          - not_null